In [1]:
# Boolean Indexing Started:
# Numpy part 3

In [2]:
import numpy as np
x = np.arange(25).reshape(5,5)
x[x>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
import numpy as np
x = np.arange(25).reshape(5,5)
x[x<10]
print(x)
print(x<10)
print(x[x<10])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
x = np.arange(25).reshape(5,5)
print(x)
print(x[x<=7])
print(x[(x > 10) & (x < 17)] == -1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[0 1 2 3 4 5 6 7]
[False False False False False False]


In [15]:
x[x>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
# Set operator:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

print('x = /n',x)
print(np.intersect1d(x,y))

x = /n [1 2 3 4 5]
[]


In [19]:
# sort
x = np.array([7,1,5,0,2,18])
print(np.sort(x))

[ 0  1  2  5  7 18]


In [21]:
x = np.random.randint(1,11,size=(10,))
print('x = \n',x)
print(np.sort(x))

x = 
 [ 1  2  7  7  8 10  7  4  2  8]
[ 1  2  2  4  7  7  7  8  8 10]


In [23]:
np.sort(np.unique(x)) # Unique values will be return and sorted

array([ 1,  2,  4,  7,  8, 10])

In [25]:
x = np.random.randint(1,11,size=(5,5))

print('x = \n',x)
print(np.sort(x , axis = 0)) # Rows are sorted of the matrix

print(np.sort(x , axis = 1)) # col are sorted of the matrix

x = 
 [[ 8  8  2  9  4]
 [ 5  3  8  6  4]
 [ 3  6  4  4 10]
 [ 6  7  8  7  8]
 [10  9  4  2  4]]
[[ 3  3  2  2  4]
 [ 5  6  4  4  4]
 [ 6  7  4  6  4]
 [ 8  8  8  7  8]
 [10  9  8  9 10]]
[[ 2  4  8  8  9]
 [ 3  4  5  6  8]
 [ 3  4  4  6 10]
 [ 6  7  7  8  8]
 [ 2  4  4  9 10]]


In [26]:
# Questions
import numpy as np
x = np.arange(25).reshape(5,5)
print(x[x % 2 != 0])

[ 1  3  5  7  9 11 13 15 17 19 21 23]
